[build]
  command = "npm install && npm run build" # Replace with your build command if needed
  functions = "functions" # Path to your serverless function
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
